% R bootcamp, Module 6: Programming
% August 2014, UC Berkeley
% Jarrod Millman
========================================================

# Problem 1


```{r}
rnormMatrix <- function(r, c) {
    return(matrix(rnorm(r*c), r))
}
```

# Problem 2

```{r}
colSums.builtin  <- function(x) {
    return(colSums(x))
}
```

# Problem 3

```{r}
colSums.apply <- function(x) {
    return(apply(x, 2, sum))
}
```

# Problem 4

```{r}
colSums.for <- function(x) {
    s <- vector("numeric", ncol(x))
    for (col in 1:ncol(x)) {
        s[col] = sum(x[,col])
    }
    return(s)
}
```

# Problem 5

```{r}
d = rnormMatrix(3, 4)
colSums.builtin(d)
colSums.apply(d)
colSums.for(d)

system.time(colSums.builtin(d))
system.time(colSums.apply(d))
system.time(colSums.for(d))

d = rnormMatrix(300, 400)
system.time(colSums.builtin(d))
system.time(colSums.apply(d))
system.time(colSums.for(d))

d = rnormMatrix(30000, 400)
system.time(colSums.builtin(d))
system.time(colSums.apply(d))
system.time(colSums.for(d))

d = rnormMatrix(300, 400000)
system.time(colSums.builtin(d))
system.time(colSums.apply(d))
system.time(colSums.for(d))

```

# Problem 5, redux

WARNING: This will take several minutes to compute.

```{r}
library(rbenchmark)

time.builtin = function(x) {
    return(benchmark(colSums.builtin(x),
           columns = c('elapsed')))
}

time.apply = function(x) {
    return(benchmark(colSums.apply(x),
           columns = c('elapsed')))
}

time.for = function(x) {
    return(benchmark(colSums.for(x),
           columns = c('elapsed')))
}

szs = seq(1000, 100000, 5000)
#szs = seq(1000, 1000000, 50000)
x = lapply(szs, rnormMatrix, 100)

for.times = sapply(x, time.for)
apply.times = sapply(x, time.apply)
builtin.times = sapply(x, time.builtin)

plot(szs, unlist(for.times), main="Benchmarks for computing column sums",
     ylab="Time elapsed", type='l', col='blue')
lines(szs, unlist(apply.times), col='red')
lines(szs, unlist(builtin.times))
legend("topleft", c("for loop","apply","builtin C function"),
      fill=c('blue','red','black'))
```

